Table albumns {
  AlbumId integer [primary key]
  ArtistId integer
  Title varchar
}

Table artists {
  ArtistId integer [primary key]
  Name varchar
}

Table customers {
  CustomerId integer [primary key]
  FirstName varchar 
  LastName varchar 
  Company varchar 
  Address varchar
  City varchar
  State varchar
  Country varchar
  PostalCode varchar
  Phone varchar
  Fax varchar
  Email varchar
  SupportRepId varchar
}

Table employees {
  EmployeeId integer [primary key]
  LastName varchar
  FirstName varchar
  Title varchar
  ReportsTo integer [note: "Joined to SupportRepId"]
  BirthDate datetime
  HireDate datetime
  Address varchar
  City varchar
  State varchar
  Country varchar
  PostalCode varchar
  Phone varchar
  Fax varchar
  Email varchar
}

Table genres {
  GenreId integer [primary key]
  Name varchar
}

Table invoice_items {
  InvoiceLineId integer [primary key]
  InvoiceId integer
  TrackId integer
  UnitPrice float [default: `FLOAT`, note: "Price per unit"]
  Quantity integer
}

Table invoices {
  InvoiceId integer [primary key]
  CustomerId integer
  InvoiceDate datetime [note: "Invoice date in format YYYY-MM-DD"]
  BillingAddress varchar
  BillingCity varchar
  BillingState varchar
  BillingCountry varchar
  BillingPostalCode varchar
}

Table media_types {
  MediaTypeId integer [primary key]
  Name varchar
}

Table playlist_track {
  PlaylistId integer [primary key]
  TrackId integer

}

Table playlists {
  PlaylistId integer [primary key]
  Name varchar
}

Table tracks {
  TrackId integer [primary key]
  Name varchar
  AlbumId integer
  MediaTypeId integer
  GenreId integer
  Composer varchar
  Milliseconds integer
  Bytes integer
  UnitPrice float
}


Ref: artists.ArtistId > albumns.ArtistId // one-to-one
Ref: invoices.InvoiceId > invoice_items.InvoiceId // one-to-one
Ref: invoice_items.TrackId > playlist_track.TrackId // one-to-one
Ref: playlist_track.PlaylistId > playlists.PlaylistId // one-to-one
Ref: tracks.TrackId > invoice_items.TrackId // one-to-one
Ref: tracks.GenreId > genres.GenreId // one-to-one
Ref: tracks.MediaTypeId > media_types.MediaTypeId // one-to-one
Ref: tracks.AlbumId > albumns.AlbumId // one-to-one
Ref: invoices.CustomerId > customers.CustomerId // one-to-one
Ref: customers.SupportRepId > employees.ReportsTo // one-to-one